### ISSUE TITLE
Dataset Questions

### ISSUE THREAD

**Issue by HenryJunW** [theopsall/Video-Summarization#1]
Impressive work! I am wondering where I can access and download the original .mp4 video and .wav audio files? In the provided Google Drive link, there are only .npy files for the groundtrunth annotation files. Thanks in advance!

**Comment by theopsall** [comment]
Thank you very much @HenryJunW  for your kind words. Due to copyright, I can not make the raw videos available, but you can find attached a txt file with a superset of the youtube URLs videos if you want to download them for non-commercial.  As for the audio data, you can get them from videos using ffmpeg. 
You can access the superset of the videos organized by category,  under the refactor branch. 
dataset: https://github.com/theopsall/Video-Summarization/tree/refactor/video_summarization/dataset

**Comment by HenryJunW** [comment]
Thanks! @theopsall  Really appreciate it very much!
